name: AWS ECR Setup
description: Authenticate AWS and login to ECR
inputs:
  aws_account_id:
    required: true
  aws_region:
    required: true
  ecr_repository:
    required: true
runs:
   using: composite
   steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::${{ inputs.aws_account_id }}:role/AwsOidcAuthRole
        aws-region: ${{ inputs.aws_region }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2
    - name: Set Image URI
      shell: bash
      run: echo "ECR Repository URI = ${{ steps.login-ecr.outputs.registry }}.dkr.ecr.${{ inputs.aws_region }}.amazonaws.com/${{ inputs.ecr_repository }}"

   