name: CI Pipeline
on:
  push:

jobs:
    build_from_org_runner:
        runs-on: my-runner
        steps:
            - name: checkout code
              uses: actions/checkout@v4

            - name: Detect branch
              run: echo "Branch is $env:GITHUB_REF"

            - name: say Hello
              run: echo "Hello from my self-hosted org runner"
  
    build_from_repo_runner:
        runs-on: self-hosted
        steps:
            - name: checkout code
              uses: actions/checkout@v4
            - name: Detect branch
              run: echo "Branch is $env:{GITHUB_REF}"
            - name: say Hello
              run: echo "Hello from my self-hosted repo runner"
    



              

                

