name: Deployment Pipeline
on:
    workflow_dispatch:
        inputs:
            environment:
                description: 'Select environment'
                required: true
                type: choice
                options:
                    - dev
                    - sit
                    - uat
                    - pnb
                    - prod
                default: 'dev'

permissions:
    id-token: write
    contents: read

jobs:
    deploy:
        runs-on: ubuntu-latest
        env:
                          # condition && value_if_true || value_if_false
            AWS_ACCOUNT_ID: "${{github.event.inputs.environment == 'prod' && 'PROD_ACCOUNT_ID' || '277707113274' }}"
            ECR_REPOSITORY: devops-lab/myapp
            AWS_REGION: ap-south-1

        steps:
            - name: checkout code
              uses: actions/checkout@v4
            - name: Print Selected Environment
              run: |
                echo "Selected environment is : ${{ github.event.inputs.environment }}"
            - name: Print AWS Account
              run: echo "AWS Account = $AWS_ACCOUNT_ID" 
            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/AwsOidcAuthRole
                aws-region: ap-south-1
                    # aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                    # aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                    # aws-region: us-east-1
                    # AwsOidcAuthRole
            - name: Verify AWS Identity
              id: login-ecr
              uses: aws-actions/amazon-ecr-login@v2


            - name: Print Image URI
              run: echo "IMAGE_URI=${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPOSITORY}" >> $GITHUB_ENV
            - name: Print Image URI
              run: echo "Image URI = $IMAGE_URI"

           